// <auto-generated />
using System;
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace animalshelterapi.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    [Migration("20200821231303_seeddata")]
    partial class seeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterApi.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Breed");

                    b.Property<DateTime>("DateOfAdmittance");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<string>("Species");

                    b.Property<string>("Url");

                    b.HasKey("CatId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            Age = 7,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 13, 3, 35, DateTimeKind.Local).AddTicks(4993),
                            Gender = "Female",
                            Name = "Catname",
                            Species = "Woolly Mammoth",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            CatId = 2,
                            Age = 7,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 13, 3, 35, DateTimeKind.Local).AddTicks(5488),
                            Gender = "Female",
                            Name = "Cat3name",
                            Species = "Woolly Mammoth",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        });
                });

            modelBuilder.Entity("AnimalShelterApi.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Breed");

                    b.Property<DateTime>("DateOfAdmittance");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<string>("Species");

                    b.Property<string>("Url");

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            Age = 7,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 13, 3, 33, DateTimeKind.Local).AddTicks(4920),
                            Gender = "Female",
                            Name = "Matilda",
                            Species = "Woolly Mammoth",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            DogId = 2,
                            Age = 10,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 13, 3, 35, DateTimeKind.Local).AddTicks(1697),
                            Gender = "Female",
                            Name = "Rexie",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            DogId = 3,
                            Age = 2,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 13, 3, 35, DateTimeKind.Local).AddTicks(1712),
                            Gender = "Female",
                            Name = "Matilda",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            DogId = 4,
                            Age = 4,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 13, 3, 35, DateTimeKind.Local).AddTicks(1716),
                            Gender = "Male",
                            Name = "Pip",
                            Species = "Shark",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            DogId = 5,
                            Age = 22,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 13, 3, 35, DateTimeKind.Local).AddTicks(1719),
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            DogId = 6,
                            Age = 22,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 13, 3, 35, DateTimeKind.Local).AddTicks(1722),
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            DogId = 7,
                            Age = 22,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 13, 3, 35, DateTimeKind.Local).AddTicks(1725),
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            DogId = 8,
                            Age = 22,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 13, 3, 35, DateTimeKind.Local).AddTicks(1728),
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            DogId = 9,
                            Age = 22,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 13, 3, 35, DateTimeKind.Local).AddTicks(1731),
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            DogId = 10,
                            Age = 22,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 13, 3, 35, DateTimeKind.Local).AddTicks(1734),
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            DogId = 11,
                            Age = 22,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 13, 3, 35, DateTimeKind.Local).AddTicks(1736),
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            DogId = 12,
                            Age = 22,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 13, 3, 35, DateTimeKind.Local).AddTicks(1739),
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            DogId = 13,
                            Age = 22,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 13, 3, 35, DateTimeKind.Local).AddTicks(1742),
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
