// <auto-generated />
using System;
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace animalshelterapi.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    [Migration("20200821171018_changelaunchsettings")]
    partial class changelaunchsettings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Breed");

                    b.Property<DateTime>("DateOfAdmittance");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<string>("Species");

                    b.Property<string>("Url");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 7,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 10, 10, 18, 535, DateTimeKind.Local).AddTicks(7263),
                            Gender = "Female",
                            Name = "Matilda",
                            Species = "Woolly Mammoth",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 10,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 10, 10, 18, 537, DateTimeKind.Local).AddTicks(4736),
                            Gender = "Female",
                            Name = "Rexie",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 2,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 10, 10, 18, 537, DateTimeKind.Local).AddTicks(4820),
                            Gender = "Female",
                            Name = "Matilda",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 4,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 10, 10, 18, 537, DateTimeKind.Local).AddTicks(4825),
                            Gender = "Male",
                            Name = "Pip",
                            Species = "Shark",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 22,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 10, 10, 18, 537, DateTimeKind.Local).AddTicks(4828),
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 22,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 10, 10, 18, 537, DateTimeKind.Local).AddTicks(4831),
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 22,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 10, 10, 18, 537, DateTimeKind.Local).AddTicks(4834),
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 22,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 10, 10, 18, 537, DateTimeKind.Local).AddTicks(4837),
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 22,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 10, 10, 18, 537, DateTimeKind.Local).AddTicks(4840),
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = 22,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 10, 10, 18, 537, DateTimeKind.Local).AddTicks(4843),
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            AnimalId = 11,
                            Age = 22,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 10, 10, 18, 537, DateTimeKind.Local).AddTicks(4846),
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            AnimalId = 12,
                            Age = 22,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 10, 10, 18, 537, DateTimeKind.Local).AddTicks(4849),
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            AnimalId = 13,
                            Age = 22,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 10, 10, 18, 537, DateTimeKind.Local).AddTicks(4852),
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
