// <auto-generated />
using System;
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace animalshelterapi.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    [Migration("20200821231028_newdogcat")]
    partial class newdogcat
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterApi.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Breed");

                    b.Property<DateTime>("DateOfAdmittance");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<string>("Species");

                    b.Property<string>("Url");

                    b.HasKey("CatId");

                    b.ToTable("Cats");
                });

            modelBuilder.Entity("AnimalShelterApi.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Breed");

                    b.Property<DateTime>("DateOfAdmittance");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<string>("Species");

                    b.Property<string>("Url");

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            Age = 7,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 10, 28, 107, DateTimeKind.Local).AddTicks(8109),
                            Gender = "Female",
                            Name = "Matilda",
                            Species = "Woolly Mammoth",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            DogId = 2,
                            Age = 10,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 10, 28, 109, DateTimeKind.Local).AddTicks(4902),
                            Gender = "Female",
                            Name = "Rexie",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            DogId = 3,
                            Age = 2,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 10, 28, 109, DateTimeKind.Local).AddTicks(4918),
                            Gender = "Female",
                            Name = "Matilda",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            DogId = 4,
                            Age = 4,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 10, 28, 109, DateTimeKind.Local).AddTicks(4921),
                            Gender = "Male",
                            Name = "Pip",
                            Species = "Shark",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            DogId = 5,
                            Age = 22,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 10, 28, 109, DateTimeKind.Local).AddTicks(4924),
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            DogId = 6,
                            Age = 22,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 10, 28, 109, DateTimeKind.Local).AddTicks(4927),
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            DogId = 7,
                            Age = 22,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 10, 28, 109, DateTimeKind.Local).AddTicks(4930),
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            DogId = 8,
                            Age = 22,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 10, 28, 109, DateTimeKind.Local).AddTicks(4933),
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            DogId = 9,
                            Age = 22,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 10, 28, 109, DateTimeKind.Local).AddTicks(4936),
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            DogId = 10,
                            Age = 22,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 10, 28, 109, DateTimeKind.Local).AddTicks(4939),
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            DogId = 11,
                            Age = 22,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 10, 28, 109, DateTimeKind.Local).AddTicks(4942),
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            DogId = 12,
                            Age = 22,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 10, 28, 109, DateTimeKind.Local).AddTicks(4945),
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            DogId = 13,
                            Age = 22,
                            Breed = "Alpine",
                            DateOfAdmittance = new DateTime(2020, 8, 21, 16, 10, 28, 109, DateTimeKind.Local).AddTicks(4948),
                            Gender = "Male",
                            Name = "Bartholomew",
                            Species = "Dinosaur",
                            Url = "https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/07/1024/512/iStock-466395505.jpg?ve=1&tl=1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
